config/routes.rb
Restapi::Application.routes.draw do
  resources :apis

end

app/models/api.rb
class Api
 @path = Rails.root + "dbfiles"

  def self.all
    arr_file_names = Array.new
    arr_files = Dir.glob(@path + "*")
    arr_files.each do |files|
      arr_file_names << files.split("/").last
    end
    return arr_file_names
  end

  def self.write(filename, param)
    File.open(@path + filename, 'w') {|f| f.write(YAML.dump(param)) }
  end

  def self.read(filename)
    content = YAML.load(File.read(@path + filename))
  end

end

app/controllers/apis_controller.rb
class ApisController < ApplicationController

  respond_to :html, :json, :xml

  def index
    @apis = Api.all
    respond_with @apis
  end

 def show
    @api = Api.read(params[:id])
    respond_with @api
 end

 def edit
    @api = Api.read(params[:id])
    @filename = params[:id]
 end

 def update
    Api.write(params[:id], params[:api])
    redirect_to "/apis"
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apis/edit.html.erb
<h1>Editing</h1>


<form accept-charset="UTF-8" action="/apis/<%= @filename %>" class="edit_api" id="edit_api_<%= @filename %>" method="post">
<div style="margin:0;padding:0;display:inline">
<input name="_method" type="hidden" value="put" />
</div>

  <div class="field">
    <label for="api_param1">Param1</label><br />
    <input id="api_param1" name="api[param1]" size="30" type="text" value="<%= @api["param1"] %>" />
  </div>
  <div class="field">
    <label for="api_param2">Param2</label><br />
    <input id="api_param2" name="api[param2]" size="30" type="text" value="<%= @api["param2"] %>" />
  </div>
  <div class="actions">
    <input name="commit" type="submit" value="Update Api" />
  </div>
</form>

<a href="/apis">Home</a>

app/views/apis/index.html.erb
<h1>Listing</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apis.each do |api| %>
  <tr>
    <td><%= api %> show: </td>
    <td><a href="/apis/<%= api %>.json" >json</a></td>
    <td><a href="/apis/<%= api %>.xml" >xml</a></td>
    <td><%= link_to 'Edit', edit_api_path(api) %></td>
  </tr>
<% end %>
</table>
<!-- http://192.168.1.42:3000/apis/1/edit -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restapi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>